# Site settings
title: Life is Hard
email: funnychen@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  console.info('I am Adobe.');
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://barrychen38.github.io' # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: barrychen38
wechat_username: wx_cyb38

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

# more_vert:
#   option1:
#     name: Cool Option 1
#     link: www.myawesomelink.com
#   option2:
#     name: Cool Option 2
#     link: www.myawesomelink.com
#   option3:
#     name: Cool Option 3
#     link: www.myawesomelink.com

disqus: false
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
